In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [2]:
df = pd.read_excel("C:/Users/NITIKA KUMARI/Downloads/Influenza_surveillance_Data.xlsx")

In [3]:
df

,Pathogen Test Result,Host Sex,Host Age,diarrhea,cough,running nose,myalgia,short breath,nausea,headache,...,Obesity,hepatobiliary_disease,respiratory_disease,urogenital_disease,Other_Chronic_Conditions,Allergies,chronic_lung_disease,Immunosuppression,autoimmune_disorder,endocrine_metabolic_disorder
0,0,1,26,0,1,1,1,1,1,1,...,1,0,0,0,1,0,1,0,0,0
1,0,0,12,0,1,1,0,1,1,1,...,0,0,0,0,1,0,0,0,0,0
2,0,1,0,1,1,1,1,0,1,1,...,1,0,0,0,0,0,0,0,0,0
3,1,1,0,0,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,20,0,1,1,0,1,1,0,...,0,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7423,1,0,67,0,1,0,1,1,0,1,...,0,1,0,0,0,0,0,0,0,0
7424,1,1,27,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7425,1,1,33,1,1,1,1,1,1,1,...,0,0,0,0,1,0,0,0,0,0
7426,0,1,14,0,1,1,0,0,0,1,...,0,0,0,0,1,0,0,0,0,0
7427,1,1,74,0,1,0,1,1,0,1,...,1,0,0,0,1,0,1,0,0,1

In [4]:
df.sample()

,Pathogen Test Result,Host Sex,Host Age,diarrhea,cough,running nose,myalgia,short breath,nausea,headache,...,Obesity,hepatobiliary_disease,respiratory_disease,urogenital_disease,Other_Chronic_Conditions,Allergies,chronic_lung_disease,Immunosuppression,autoimmune_disorder,endocrine_metabolic_disorder
5856,0,1,4,0,1,1,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [5]:
df.columns

Index(['Pathogen Test Result', 'Host Sex', 'Host Age', 'diarrhea', 'cough',
       'running nose', 'myalgia', 'short breath', 'nausea', 'headache',
       'malaise', 'throat', 'fever',
       'Acquired absence of right and left ankle', 'TB', 'hyperlipidemia',
       'Recurrent Otitis Media', 'acid reflux', 'glaucoma', 'Asthma', 'Cancer',
       'Cardiovascular_disease', 'hematological_disease', 'migraines_updated',
       'neurologic_disorder', 'Obesity', 'hepatobiliary_disease',
       'respiratory_disease', 'urogenital_disease', 'Other_Chronic_Conditions',
       'Allergies', 'chronic_lung_disease', 'Immunosuppression',
       'autoimmune_disorder', 'endocrine_metabolic_disorder'],
      dtype='object')

In [6]:
# Target
y = df['Pathogen Test Result']

# Features (drop target)
X = df.drop('Pathogen Test Result', axis=1)

In [7]:
X = X.replace({'Yes':1, 'No':0})

In [8]:
X = pd.get_dummies(X, drop_first=True)

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42,stratify=y
)

In [10]:
rf = RandomForestClassifier(
    n_estimators=200,      # number of trees
    max_depth=10,          # tree depth 
    min_samples_split=5,   # min samples to split a node
    min_samples_leaf=2,
)

In [13]:
rf.fit(X_train, y_train)
gb.fit(X_train,y_train)
svc.fit(X_train, y_train)

SVC()

In [14]:
y_rf = rf.predict(X_test)
y_svc = svc.predict(X_test)
y_gb = gb.predict(X_test)

In [15]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Accuracy_gb:", accuracy_score(y_test, y_gb))
print("Accuracy_svc:", accuracy_score(y_test, y_svc))
print("Accuracy_rf:", accuracy_score(y_test, y_rf))

Accuracy_gb: 0.7375504710632571
Accuracy_svc: 0.6594885598923284
Accuracy_rf: 0.7745625841184388

In [84]:
#GRIDSEARCH

In [18]:
from sklearn.model_selection import GridSearchCV

In [19]:
rf_param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [5, 10, 15],
    'min_samples_split': [2, 5]
}

In [36]:
gb_param_grid = {
    'n_estimators': [100, 200, 300],
    'learning_rate': [0.01,0.1,0.5],
    'estimator__max_depth':[1,2,3]
}

In [37]:
grid_search = GridSearchCV(
    estimator= rf,
    param_grid=param_grid,
    cv=5,
    scoring='accuracy',
    n_jobs =-1,
    verbose =2,
   
)

In [44]:
gb_grid_search = GridSearchCV(
    estimator= gb,
    param_grid=param_grid_gb,
    cv=5,
    scoring='accuracy',
    n_jobs =-1,
    verbose =2,
)

In [ ]:
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

In [40]:
grid_search_gb.fit(X_train, y_train)

Fitting 5 folds for each of 27 candidates, totalling 135 fits

ValueError: Invalid parameter 'estimator' for estimator GradientBoostingClassifier(). Valid parameters are: ['ccp_alpha', 'criterion', 'init', 'learning_rate', 'loss', 'max_depth', 'max_features', 'max_leaf_nodes', 'min_impurity_decrease', 'min_samples_leaf', 'min_samples_split', 'min_weight_fraction_leaf', 'n_estimators', 'n_iter_no_change', 'random_state', 'subsample', 'tol', 'validation_fraction', 'verbose', 'warm_start'].

In [ ]:
best_model = grid_search.best_estimator_

In [ ]:
best_model_gb = gb_grid_search.best_estimator_

In [94]:
print(grid_search.best_params_)

{'max_depth': 15, 'min_samples_split': 2, 'n_estimators': 300}

In [ ]:
print(grid_search.best_params_)

In [95]:
y_pred = best_model.predict(X_test)

In [96]:
y_pred = best_model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Test Accuracy:", accuracy)

Test Accuracy: 0.8546433378196501